language: node_js

node_js:
  - "6"

cache:
  directories:
    - "node_modules"

install:
  - npm install
script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: /
  on:
    branch: master
    target_branch: gh-pages