language: node_js

node_js:
  - "8"

cache:
  directories:
    - "node_modules"

install:
  - npm install
script:
  - npm run build

deploy:
  provider: pages
  edge:
    branch: v1.8.47
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
